[options]
admin_passwd = TU_PASSWORD_AQUI
db_host = localhost
db_port = 5432
db_user = odoo18
db_password = TU_PASSWORD_AQUI
addons_path = /opt/odoo18/odoo18/addons,/opt/odoo18/odoo18/custom-addons
logfile = /var/log/odoo18/odoo.log
xmlrpc_port = 8069
proxy_mode = True
